# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QBQqBKR_tk3XjNWaDfbPO0h55vik_Wzn
"""

# Step 2: Save the Streamlit code to a Python file
with open('app.py', 'w') as f:
    f.write("""
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Forecasted Data (Replace with actual forecast data paths)
forecast_df = pd.read_csv('/content/forecasted_portfolio.csv', parse_dates=['Date'], index_col='Date')
returns = forecast_df.pct_change().dropna()

# Function to calculate portfolio metrics
def portfolio_stats(weights, returns):
    portfolio_return = np.sum(weights * returns.mean()) * 252
    portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(returns.cov() * 252, weights)))
    sharpe_ratio = portfolio_return / portfolio_volatility
    return portfolio_return, portfolio_volatility, sharpe_ratio

# Streamlit App Layout
st.title("Interactive Portfolio Dashboard")

st.sidebar.header("Adjust Portfolio Allocation")
tsla_weight = st.sidebar.slider("Tesla (TSLA) Weight", 0.0, 1.0, 0.33, 0.01)
bnd_weight = st.sidebar.slider("BND Weight", 0.0, 1.0, 0.33, 0.01)
spy_weight = st.sidebar.slider("SPY Weight", 0.0, 1.0, 0.34, 0.01)

# Normalize Weights
weights = np.array([tsla_weight, bnd_weight, spy_weight])
weights /= np.sum(weights)  # Ensure weights sum to 1

# Calculate Portfolio Metrics
portfolio_return, portfolio_volatility, sharpe_ratio = portfolio_stats(weights, returns)

# Display Portfolio Metrics
st.subheader("Portfolio Performance")
st.write(f"**Expected Annual Return:** {portfolio_return:.2f}")
st.write(f"**Portfolio Volatility:** {portfolio_volatility:.2f}")
st.write(f"**Sharpe Ratio:** {sharpe_ratio:.2f}")

# Plot Cumulative Returns
st.subheader("Portfolio Cumulative Returns")
cum_returns = (1 + returns @ weights).cumprod()
plt.figure(figsize=(10,5))
plt.plot(cum_returns, label="Portfolio")
plt.legend()
st.pyplot(plt)

st.write("Adjust the weights using the sidebar to see how it impacts the portfolio performance.")
""")

!ls